commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('new', views.create_listing, name='new'),
    path('list_filter', views.list_filter, name='list_filter'),
    path('listing/<int:id>', views.listing, name='listing'),
    path('removeWatchlistOnListingPage/<int:id>', views.remove_watchlist_on_listing_page, name='removeWatchlistOnListingPage'),
    path('removeEntryInWatchlist/<int:id>', views.remove_entry_in_watchlist, name='removeEntryInWatchlist'),
    path('addWatchlist/<int:id>', views.add_watchlist, name='addWatchlist'),
    path('watchlist', views.view_watchlist, name='watchlist'),
    path('add_comment/<int:id>', views.add_comment, name='add_comment'),
    path('make_bid/<int:id>', views.make_bid, name='make_bid'),
    path('close_listing/<int:id>', views.close_listing, name='close_listing'),
    path('brands', views.brands, name='brands'),
    path('brands/<int:id>', views.brand_entries, name='brand_entries'),
    path('users/<int:id>', views.users, name='users'),
    path('users/<int:id>/entries', views.user_entries, name='user_entries'),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("auctions.urls", 'auctions'), namespace='auctions'))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Brand(models.Model):
    name = models.CharField(max_length=64)
    image_url = models.CharField(max_length=300, default='No image.')

    def __str__(self):
        return self.name


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user_bid')
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.amount)


class AuctionListing(models.Model):
    title = models.CharField(max_length=64)
    price = models.ForeignKey(Bid, on_delete=models.CASCADE, blank=True, null=True, related_name='bid_amount')
    image_url = models.CharField(max_length=300, default='No image.')
    description = models.CharField(max_length=1000, default='No description.')
    created = models.DateField(auto_now_add=True)
    isActive = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True, related_name='category')
    watchlist = models.ManyToManyField(User, blank=True, null=True, related_name='itemlist')

    def __str__(self):
        return self.title.title()


class Comment(models.Model):
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, blank=True, null=True, related_name='listing_com')
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user_com')
    content = models.CharField(max_length=300)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} commented on {self.listing}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import random

from .models import User, Brand, AuctionListing, Comment, Bid


def random_selection(size):
    try:
        k = random.sample(range(0, size), 5)
        selection = []
        all_entries = AuctionListing.objects.filter(isActive=True).all()
        for idx in k:
            selection.append(all_entries[idx])
        return selection
    except ValueError:
        print('Sample size exceeded population size.')


def index(request):
    allAuctions = AuctionListing.objects.filter(isActive=True).all()
    allBrands = Brand.objects.all()
    return render(request, "auctions/index.html", {
        'auctions': allAuctions, 
        'brands': allBrands, 
        'activate': True
    })


def create_listing(request):
    if request.method == "GET":
        allBrands = Brand.objects.all()
        return render(request, 'auctions/new.html', {
            'brands': allBrands
        })
    else:
        user = request.user
        title = request.POST['title']
        price = request.POST['price']
        bid = Bid(amount=float(price), user=user)
        bid.save()
        imageurl = request.POST['imageurl']
        description = request.POST['description']
        brand = request.POST['brand']
        brand_data = Brand.objects.get(name=brand)
        new = AuctionListing(
            title=title, price=bid,
            image_url=imageurl, description=description,
            author=user, brand=brand_data
        )
        new.save()
        return HttpResponseRedirect(reverse('auctions:index'))


def brands(request):
    allBrands = Brand.objects.all()
    return render(request, 'auctions/brands.html', {
        'allBrands': allBrands, 
        'msg': 'There is no available brands.'
    })


def list_filter(request):
    if request.method == 'POST':
        select = request.POST['brand']
        if select == 'All brands':
            brand = Brand.objects.all()
            allAuctions = AuctionListing.objects.filter(isActive=True).all()
        else:
            brand = Brand.objects.get(name=select)
            allAuctions = AuctionListing.objects.filter(isActive=True, brand=brand).all()
        if len(allAuctions) == 0:
            msg = 'Currently, there is no listings of a particular brand.'
        else:
            msg = None
        allBrands = Brand.objects.all()
        return render(request, "auctions/index.html", {
            'auctions': allAuctions, 
            'brands': allBrands,
            'msg': msg,
            'activate': True
        })


def brand_entries(request, id):
    allAuctions = AuctionListing.objects.filter(isActive=True, brand=id).all()
    if len(allAuctions) == 0:
        msg = 'Currently, there is no listings of a particular brand.'
    else:
        msg = None
    allBrands = Brand.objects.all()
    return render(request, "auctions/index.html", {
            'auctions': allAuctions, 
            'brands': allBrands,
            'msg': msg,
            'activate': True
        })


def listing(request, id):
    entry = get_object_or_404(AuctionListing, id=id)
    entry_in_watchlist = request.user in entry.watchlist.all()
    all_comments = Comment.objects.filter(listing=entry).all()
    if len(all_comments) == 0:
        msg = 'No comments yet. Be the first one to comment...'
    else:
        msg = None
    isOwner = request.user.username == entry.author.username
    selection = random_selection(len(AuctionListing.objects.filter(isActive=True).all()))
    return render(request, 'auctions/listing.html', {
        'entry': entry,
        'entry_in_watchlist': entry_in_watchlist,
        'all_comment': all_comments,
        'msg': msg, 
        'isOwner': isOwner, 
        'selection': selection, 
        'isNotActive': 'This auction is not longer active.'
    })


def remove_watchlist_on_listing_page(request, id):
    listing_data = AuctionListing.objects.get(pk=id)
    user = request.user
    listing_data.watchlist.remove(user)
    return HttpResponseRedirect(reverse('auctions:listing', args=(id,)))


def remove_entry_in_watchlist(request, id):
    listing_data = AuctionListing.objects.get(pk=id)
    user = request.user
    listing_data.watchlist.remove(user)
    return HttpResponseRedirect(reverse('auctions:watchlist'))


def add_watchlist(request, id):
    listing_data = AuctionListing.objects.get(pk=id)
    user = request.user
    listing_data.watchlist.add(user)
    return HttpResponseRedirect(reverse('auctions:listing', args=(id,)))


def view_watchlist(request):
    user = request.user
    all_listing_data = user.itemlist.all()
    allBrands = Brand.objects.all()
    if len(all_listing_data) == 0:
        msg = 'Your Watchlist is empty.'
    else: msg = None
    return render(request, 'auctions/watchlist.html', {
        'all_listing_data': all_listing_data,
        'allBrands': allBrands, 
        'msg': msg
    })


def add_comment(request, id):
    if request.method == 'POST':
        user = request.user
        listing_data = AuctionListing.objects.get(pk=id)
        content = request.POST.get('comment')
        new_comment = Comment(
            listing=listing_data,
            author=user, 
            content=content)
        new_comment.save()
        return HttpResponseRedirect(reverse('auctions:listing', args=(id,)))


def make_bid(request, id):
    if request.method == 'POST':
        user = request.user
        entry = AuctionListing.objects.get(pk=id)
        bid = float(request.POST['bid'])
        all_comments = Comment.objects.filter(listing=entry).all()
        selection = random_selection(len(AuctionListing.objects.filter(isActive=True).all()))
        isOwner = request.user.username == entry.author.username
        if len(all_comments) == 0:
            msg = 'No comments yet. Be the first one to comment...'
        else:
            msg = None
        if bid > float(entry.price.amount):
            new_bid = Bid(
                user=user,
                amount=bid
            )
            new_bid.save()
            entry.price = new_bid
            entry.save()
            return render(request, 'auctions/listing.html', {
                'entry': entry,
                'bid_msg': 'Your bid was accepted.', 
                'success': True,
                'all_comment': all_comments,
                'isOwner': isOwner, 
                'selection': selection, 
                'msg': msg,
                'isNotActive': 'This auction is not longer active.'
            })
        else:
            return render(request, 'auctions/listing.html', {
                'entry': entry,
                'bid_msg': 'Your bid must be higher than the current bid!', 
                'success': False,
                'all_comment': all_comments,
                'isOwner': isOwner, 
                'selection': selection, 
                'msg': msg,
                'isNotActive': 'This auction is not longer active.'

            }) 


def close_listing(request, id):
    entry = AuctionListing.objects.get(id=id)
    entry.isActive = False
    entry.save()

    entry_in_watchlist = request.user in entry.watchlist.all()
    isOwner = request.user.username == entry.author.username
    all_comments = Comment.objects.filter(listing=entry).all()
    if len(all_comments) == 0:
        msg = 'No comments yet. Be the first one to comment...'
    else:
        msg = None
    selection = random_selection(len(AuctionListing.objects.filter(isActive=True).all()))

    return render(request, 'auctions/listing.html', {
        'entry': entry,
        'entry_in_watchlist': entry_in_watchlist,
        'all_comment': all_comments,
        'msg': msg, 
        'isOwner': isOwner, 
        'selection': selection, 
        'success': True, 
        'closing_msg': 'Your auction was closed successfully.',
        'isNotActive': 'This auction is not longer active.'
    })


def users(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, 'auctions/users.html', {
        'user': user
    })


def user_entries(request, id):
    allAuctions = AuctionListing.objects.filter(isActive=True, author=id).all()
    if len(allAuctions) == 0:
        msg = 'Currently, there is no listings from a particular user.'
    else:
        msg = None
    allBrands = Brand.objects.all()
    return render(request, "auctions/index.html", {
            'auctions': allAuctions, 
            'brands': allBrands,
            'msg': msg
        })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:

commerce/auctions/templates/auctions/brands.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Brands</h2>
    {% if allBrands is None %}
        <h5>{{ msg }}</h5>
    {% endif %}
    <div class="row">
        {% for brand in allBrands %}
                <div class="col-md-12 mx-3 my-3">
                    <div class="card" style="height:10em;">
                        <div class="row card-body d-flex align-items-center">
                           <div class="col-md-6">
                                <h3 class="card-text"><strong>{{ brand.name }}</strong></h3>
                            </div>
                            <img class="col-sm-6" src="{{ brand.image_url }}" alt="No Image" style="width: 100%; height: 10vh; object-fit: contain;">
                        </div>
                        <a href="{% url 'auctions:brand_entries' id=brand.id %}" class="stretched-link"></a>
                    </div>
                </div>
        {% endfor %}
    </div>           
{% endblock %}

commerce/auctions/templates/auctions/error404.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    {% if activate %}
        <form action="{% url 'auctions:list_filter' %}" method="POST">
            <div class="form-row">
                <div class="col-auto">
                    {% csrf_token %}
                    <select class="form-control" name="brand" id="brand">
                        <option value="All brands">All brands</option>
                        {% for brand in brands %}
                            <option value="{{ brand }}">{{ brand }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input class="btn btn-outline-primary mx-3" type="submit" value="Select">
            </div>
        </form>
        <br>
    {% endif %}
    {% if msg %}
        <h5>{{ msg }}</h5>
    {% endif %}
    <div class="row row-cols-6">
        {% for auction in auctions %}
            <div class="card h-10 position-relative" style="width: 18rem; margin-left: 50px; margin-bottom: 30px;">
                <img src="{{ auction.image_url }}" class="card-img-top" alt="No Image" style="width: 100%; height: 50vh; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title mb-2">{{ auction.title }}</h5>
                    <p class="card-text mb-2">${{ auction.price.amount }}</p>
                    <a href="{% url 'auctions:listing' id=auction.id %}" class="btn btn-primary mb-2 stretched-link">View</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <div class="col-md-12">
            <ul class="nav nav-pills my-3">
                <li class="nav-item">
                    <a class="btn btn-primary mx-3" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-primary mx-3" href="{% url 'auctions:brands' %}">Brands</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-outline-primary mx-3" href="{% url 'auctions:new' %}">New Auction</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-primary mx-3" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                    </li>
                    <li class="nav-item ml-auto">
                        <a class="btn btn-outline-danger mx-3" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item ml-auto">
                        <a class="btn btn-outline-primary mx-3" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active mx-3" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if bid_msg %}
        {% if success %}
            <div class="alert alert-success" role="alert">
                {{ bid_msg }}
            </div>
        {% else %}
            <div class="alert alert-danger" role="alert">
                {{ bid_msg }}
            </div>
        {% endif %}
    {% endif %}
    {% if closing_msg %}
        <div class="alert alert-success" role="alert">
            {{ closing_msg }}
        </div>
    {% endif %}
    {% if not entry.isActive %}
        {% if user == entry.price.user %}
            {% if entry.price.user == entry.author %}
            <div class="alert alert-warning" role="alert">
                Your item was not sold.
            </div>
            {% else %}
            <div class="alert alert-success" role="alert">
                Congratulations! You won the auction!
            </div>
            {% endif %}
        {% else %}
            <div class="alert alert-danger" role="alert">
                This auction is no longer active. 
            </div>
        {% endif %}
    {% endif %}


    <div class='row mx-4'>
        {% if user.is_authenticated and entry.isActive %}
            {% if entry_in_watchlist %}
                <form action="{% url 'auctions:removeWatchlistOnListingPage' id=entry.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove From Watchlist</button>
                </form>
            {% else %}
                <form action="{% url 'auctions:addWatchlist' id=entry.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary mx-3">Add to Watchlist</button>
                </form>
            {% endif %}
            {% if isOwner %}
                <form action="{% url 'auctions:close_listing' id=entry.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mx-3">Close Listing</button>
                </form>
            {% endif %}
        {% endif %}
    </div>
    <br>
    <div class="row mx-4">
        <div class="col-md-3">
            <div class="card mx-auto h-100">
                <div class="card-body">
                    <h2 class="card-title">{{ entry.title }}</h2>
                    <h4 class="card-text"><strong>${{ entry.price.amount }}</strong></h4>
                    <img class="card-img-bottom mx-auto" id='entry' src="{{ entry.image_url }}" class="card-img-bottom" alt="No Image" style="width: 100%; height: 50vh; object-fit: cover;">
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto" style="height: auto;">
                <div class="card-body">
                    <h3 class="card-title">Details:</h3>
                    <p class="card-text">{{ entry.description }}</p>
                    <p class="card-text">Brand: <a href="{% url 'auctions:brand_entries' id=entry.brand.id %}">{{ entry.brand }}</a></p>
                    <p class="card-text">Uploaded by <a href="{% url 'auctions:users' id=entry.author.id %}">{{ entry.author }}</a></p>
                    <p class="card-text">Uploaded on {{ entry.created }}</p>
                </div>
            </div>
            <br>
            {% if user.is_authenticated and entry.isActive %}
                <div class="card mx-auto" style="height: auto;">
                    <div class="card-body">
                        <h3 class="card-title">Bids:</h3>
                        <form action="{% url 'auctions:make_bid' id=entry.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <p>Current highest bid is <strong>${{ entry.price.amount }}</strong></p>
                                <input type="number" name="bid" class="form-control" id="price" min="0" placeholder="Enter bid">
                            </div>
                            <button type="submit" class="btn btn-primary">Bid</button>
                        </form>
                    </div>
                </div>
            {% else %}
            <div class="card mx-auto" style="height: auto;">
                <div class="card-body">
                    <h3 class="card-title">Bids:</h3>
                    <form action="{% url 'auctions:make_bid' id=entry.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {% if entry.isActive %}
                                <p>The current highest bid is <strong>${{ entry.price.amount }}</strong></p>
                                <input type="number" name="bid" class="form-control" id="price" min="0" placeholder="You must be logged in to make a bid offer..." readonly>
                            {% else %}
                                <p>The highest bid was <strong>${{ entry.price.amount }}</strong></p>
                                <input type="number" name="bid" class="form-control" id="price" min="0" placeholder="The auction is no longer active..." readonly>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary" disabled>Bid</button>
                    </form>
                </div>
            </div>
            {% endif %}
            <br>
            <div class="row row-cols-6">
                {% for auction in selection %}
                    <div class="card mx-auto" style="height: 250px;">
                        <img src="{{ auction.image_url }}" class="card-img-top" alt="No Image" style="width: 100%; height: 16vh; object-fit: contain;">
                        <div class="card-body">
                            <h5 class="card-text">{{ auction.title }}</h5>
                            <p class="card-text">${{ auction.price.amount }}</p>
                            <a href="{% url 'auctions:listing' id=auction.id %}" class="stretched-link"></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <div class="row mx-1">
        <div class="col md-12">
            <div class="card-body">
                <h3 class="card-title">Comments:</h3>
                {% if user.is_authenticated %}
                    <form action="{% url 'auctions:add_comment' id=entry.id %}" method="POST">
                        <textarea class="form-control" name="comment" rows="3" placeholder="Comment"></textarea>
                        {% csrf_token %}
                        <br>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </form>
                    <br>
                {% else %}
                    <form action="{% url 'auctions:add_comment' id=entry.id %}" method="POST">
                        <textarea class="form-control" name="comment" rows="3" placeholder="You must be logged in to comment..." readonly></textarea>
                        {% csrf_token %}
                        <br>
                        <button type="submit" class="btn btn-primary" disabled>Post</button>
                    </form>
                    <br>
                {% endif %}
                {% if msg %}
                    <h5>{{ msg }}</h5>
                {% endif %}
                {% for comment in all_comment %}
                    <div class="col md-12">
                        <div class="card mx-auto">
                            <div class="card-body">
                                <h5 class="card-title"><a href="#">{{ comment.author }}:</a></h5>
                                <p class="card-text">{{ comment.content }}</p>
                                <p class="card-footer">Uploaded on {{ comment.created }}</p>
                                <hr>
                            </div>
                        </div>
                        <br>
                    </div>
                {% endfor %}
            </div>  
        </div>
    </div>
{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}


{% block title %}New Auction{% endblock %}


{% block body %}
    <h2>New Auction</h2>

    <form action="{% url 'auctions:new' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control" id="title" placeholder="Enter title">
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="number" min="0" name="price" class="form-control" id="price" placeholder="Enter price">
        </div>
        <div class="form-group">
            <label for="imageurl">Image URL</label>
            <input type="text" name="imageurl" class="form-control" id="imageurl" placeholder="Enter image URL">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="description" class="form-control" id="description" placeholder="Enter description">
        </div>
        <div>
            <label for="brand">Brand</label>
            <br>
            <select class="form-select" name="brand" id="brand">
                <option selected>Select brand</option>
                {% for brand in brands %}
                    <option value="{{ brand }}">{{ brand }}</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <input class="btn btn-primary" type="submit" value="Create New Auction">
        
    </form>
{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/users.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>User <strong>{{ user.username }}</strong> contact information</h2>
    <ul>
        <li>Name: {{ user.first_name }}</li>
        <li>Email: {{ user.email }}</li>
        <li>Phone Number:</li>
        <li>City:</li>
        <li>Last Login: {{ user.last_login }}</li>
    </ul>
    <a class="btn btn-outline-primary mx-3" href="{% url 'auctions:user_entries' id=user.id %}">Search for User's Active Listings</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Your Watchlist</h2>
    {% if msg %}
        <br>
        <h5>{{ msg }}</h5>
    {% endif %}
    <div class="row row-cols-6">
        {% for auction in all_listing_data %}
            <div class="card h-10" style="width: 18rem; margin-left: 30px;">
                <img src="{{ auction.image_url }}" class="card-img-top" alt="No Image" style="width: 100%; height: 50vh; object-fit: contain;">
                <div class="card-body">
                    <h5 class="card-title mb-2">{{ auction.title }}</h5>
                    <p class="card-text mb-2" >${{ auction.price.amount }}</p>
                    <a href="{% url 'auctions:listing' id=auction.id %}" class="btn btn-primary mb-2 stretched-link">View</a>
                    <a href="{% url 'auctions:removeEntryInWatchlist' id=auction.id %}" class="btn btn-danger mb-2">Remove</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}